version: '3'

#prod
services:
  orthanc:
    container_name: orthanc
    image: jodogne/orthanc-plugins
    environment:
      - ORTHANC_DICOM_AET=NEW_AET
    ports:
      - 4242:4242
      - 8042:8042
    volumes:
      # - ./orthanc_data:/var/lib/orthanc/db
      - ./orthanc.json:/etc/orthanc/orthanc.json
  nginx:
    image: nginx:1.16.1
    ports:
      - 8080:80
      - 8444:443
    volumes:
      - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
  front-service:
    container_name: web
    build:
      context: ./orthanc_web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
# dev
# services:
#   orthanc:
#     image: jodogne/orthanc-plugins
#     ports:
#       - 4242:4242
#       - 8042:8042
#     volumes:
#       - ./orthanc_data:/var/lib/orthanc/db
#   nginx:
#     image: nginx:1.16.1
#     ports:
#       - 8080:80
#       - 8443:443
#     volumes:
#       - ${NGINX_DEFAULT_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
  # front-service:
  #   container_name: web
  #   build:
  #     context: ./orthanc_web
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
